apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-demo-app-sb230
  name: k8s-demo-app-sb230
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app-sb230
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-demo-app-sb230
    spec:
      containers:
      - image: omcfig/k8s-demo-app-sb230
        name: k8s-demo-app-sb230
        resources: {}
status: {}
